---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: centos-6.7
    driver:
      box: bento/centos-6.7

suites:
  - name: default
    run_list:
      - recipe[happy_filebeat_cookbook::default]
    attributes:
      filebeat:
        environment: "staging1"
        elastic:
          url: "https://0129136b2db263670ea80e2e2ec86757.us-east-1.aws.found.io:9243"
          user: "prometeo"
          pass: "test1234"
